
let userName = prompt('What is your name?');
console.log(userName);

let age = prompt('How old are you?');
console.log(age);

let City = prompt ('What is your favourite city?')
console.log(City);

let Food = prompt (' what is your favourite food?')
console.log(Food);


document.write(' Welcome '+ userName+ 'you are: ' + age + ' your favourite City is: '+ City +  ' and your favourite food is: ' + Food);
console.log();
